applicationName: telus-cio-roadmap
type: service
environment: st
image:
  repository: northamerica-northeast1-docker.pkg.dev/cio-gke-devops-e4993356/applications/cio-productops/telus-cio-roadmap
  tag: latest
serviceAccountName: cicd-service-account@cio-productops-np-a332e6.iam.gserviceaccount.com
ingress: all
iap:
  enabled: false
invokerIam:
  disabled: true
traffic: {}
sessionAffinity: false
secretEnv:
  - name: DATABASE_URL
    secret: telus-cio-roadmap-database-url
    version: latest
  - name: ANTHROPIC_API_KEY
    secret: telus-cio-roadmap-anthropic-api-key
    version: latest
  - name: NEXTAUTH_SECRET
    secret: telus-cio-roadmap-nextauth-secret
    version: latest
  - name: NEXTAUTH_URL
    secret: telus-cio-roadmap-nextauth-url
    version: latest
